#!/bin/bash

# Protobuf Code Generation Script for Ecliptix iOS
# Generates Swift code from .proto files using protoc

set -e

echo "🔧 Ecliptix iOS - Protobuf Code Generation"
echo "=========================================="

# Configuration
PROTO_DIR="./Protos"
OUTPUT_DIR="./Packages/EcliptixCore/Sources/Generated"
TEMP_DIR="./Packages/EcliptixCore/Sources/Generated/Proto"

# Check if protoc is installed
if ! command -v protoc &> /dev/null; then
    echo "❌ Error: protoc not found"
    echo "Please install protobuf compiler:"
    echo "  brew install protobuf"
    exit 1
fi

# Check if swift-protobuf plugin is available
if ! command -v protoc-gen-swift &> /dev/null; then
    echo "❌ Error: protoc-gen-swift not found"
    echo "Please install swift-protobuf plugin:"
    echo "  brew install swift-protobuf"
    exit 1
fi

# Check if grpc-swift plugin is available
if ! command -v protoc-gen-grpc-swift &> /dev/null; then
    echo "❌ Error: protoc-gen-grpc-swift not found"
    echo "Please install grpc-swift plugin:"
    echo "  Swift Package Manager will provide this via dependencies"
    echo "  Or manually: https://github.com/grpc/grpc-swift"
    echo ""
    echo "⚠️  Continuing without gRPC service generation..."
    SKIP_GRPC=1
fi

echo ""
echo "📦 Found protoc: $(protoc --version)"
echo ""

# Create output directory
mkdir -p "$OUTPUT_DIR"
mkdir -p "$TEMP_DIR"

# Find all .proto files
PROTO_FILES=$(find "$PROTO_DIR" -name "*.proto")
PROTO_COUNT=$(echo "$PROTO_FILES" | wc -l | tr -d ' ')

echo "📝 Found $PROTO_COUNT proto files"
echo ""

# Generate Swift code
echo "🔨 Generating Swift protobuf code..."

for proto_file in $PROTO_FILES; do
    echo "  → $(basename $proto_file)"

    # Generate Swift message code
    protoc \
        --proto_path="$PROTO_DIR" \
        --swift_out="$TEMP_DIR" \
        "$proto_file"

    # Generate gRPC service code (if plugin available)
    if [ -z "$SKIP_GRPC" ]; then
        if grep -q "service " "$proto_file"; then
            echo "    (generating gRPC service)"
            protoc \
                --proto_path="$PROTO_DIR" \
                --grpc-swift_out="$TEMP_DIR" \
                "$proto_file"
        fi
    fi
done

echo ""
echo "✅ Code generation complete!"
echo ""
echo "📊 Generated files:"
GENERATED_COUNT=$(find "$TEMP_DIR" -name "*.swift" | wc -l | tr -d ' ')
echo "  Swift files: $GENERATED_COUNT"
echo "  Location: $TEMP_DIR"
echo ""

# Create index file for easy imports
echo "📝 Creating import index..."
cat > "$OUTPUT_DIR/ProtoImports.swift" << 'EOF'
// Auto-generated protobuf imports
// Generated by generate-protos.sh

// This file provides a convenient way to import all generated protobuf types
// Import this in your service clients instead of individual proto files

@_exported import SwiftProtobuf

// Note: Individual proto-generated files are in ./Generated/Proto/
// You can import them directly or use this convenience file
EOF

echo "✅ Import index created: $OUTPUT_DIR/ProtoImports.swift"
echo ""

# Summary
echo "🎉 Protobuf generation completed successfully!"
echo ""
echo "Next steps:"
echo "  1. Review generated files in: $TEMP_DIR"
echo "  2. Update Package.swift to include Generated sources"
echo "  3. Update service clients to import generated code"
echo "  4. Build project: swift build"
echo ""

# Note about manual integration
cat << 'EOF'
⚠️  IMPORTANT: Manual Steps Required

Since we're using a placeholder approach, you'll need to:

1. Add the Generated directory to your Package.swift:

   .target(
       name: "EcliptixCore",
       dependencies: [...],
       path: "Sources",
       sources: [".", "Generated/Proto"]
   )

2. The generated files use SwiftProtobuf types like:
   - Message (base protocol for all messages)
   - Google_Protobuf_Timestamp
   - Google_Protobuf_Empty

3. Service clients will import like:
   import Ecliptix_Protobuf_Membership_MembershipServices
   import Ecliptix_Protobuf_Device_DeviceService

4. Replace placeholder service calls in:
   - MembershipServiceClient.swift
   - DeviceServiceClient.swift
   - SecureChannelServiceClient.swift

EOF
