// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: device/application_settings.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Ecliptix_Proto_Device_ApplicationInstanceSettings: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Application Identity
  public var appInstanceID: Data = Data()

  public var deviceID: Data = Data()

  /// Device Information
  public var systemDeviceIdentifier: String = String()

  public var serverPublicKey: Data = Data()

  /// Localization
  public var culture: String = String()

  public var country: String = String()

  public var ipAddress: String = String()

  /// State
  public var isNewInstance: Bool = false

  /// Membership
  public var membership: Ecliptix_Proto_Membership_Membership {
    get {return _membership ?? Ecliptix_Proto_Membership_Membership()}
    set {_membership = newValue}
  }
  /// Returns true if `membership` has been explicitly set.
  public var hasMembership: Bool {return self._membership != nil}
  /// Clears the value of `membership`. Subsequent reads from it will return its default value.
  public mutating func clearMembership() {self._membership = nil}

  /// Current Account
  public var currentAccountID: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _membership: Ecliptix_Proto_Membership_Membership? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "ecliptix.proto.device"

extension Ecliptix_Proto_Device_ApplicationInstanceSettings: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ApplicationInstanceSettings"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "app_instance_id"),
    2: .standard(proto: "device_id"),
    3: .standard(proto: "system_device_identifier"),
    4: .standard(proto: "server_public_key"),
    5: .same(proto: "culture"),
    6: .same(proto: "country"),
    7: .standard(proto: "ip_address"),
    8: .standard(proto: "is_new_instance"),
    9: .same(proto: "membership"),
    10: .standard(proto: "current_account_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.appInstanceID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.systemDeviceIdentifier) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.serverPublicKey) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.culture) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.country) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.ipAddress) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.isNewInstance) }()
      case 9: try { try decoder.decodeSingularMessageField(value: &self._membership) }()
      case 10: try { try decoder.decodeSingularBytesField(value: &self.currentAccountID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.appInstanceID.isEmpty {
      try visitor.visitSingularBytesField(value: self.appInstanceID, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularBytesField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.systemDeviceIdentifier.isEmpty {
      try visitor.visitSingularStringField(value: self.systemDeviceIdentifier, fieldNumber: 3)
    }
    if !self.serverPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.serverPublicKey, fieldNumber: 4)
    }
    if !self.culture.isEmpty {
      try visitor.visitSingularStringField(value: self.culture, fieldNumber: 5)
    }
    if !self.country.isEmpty {
      try visitor.visitSingularStringField(value: self.country, fieldNumber: 6)
    }
    if !self.ipAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.ipAddress, fieldNumber: 7)
    }
    if self.isNewInstance != false {
      try visitor.visitSingularBoolField(value: self.isNewInstance, fieldNumber: 8)
    }
    try { if let v = self._membership {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
    } }()
    if !self.currentAccountID.isEmpty {
      try visitor.visitSingularBytesField(value: self.currentAccountID, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Device_ApplicationInstanceSettings, rhs: Ecliptix_Proto_Device_ApplicationInstanceSettings) -> Bool {
    if lhs.appInstanceID != rhs.appInstanceID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.systemDeviceIdentifier != rhs.systemDeviceIdentifier {return false}
    if lhs.serverPublicKey != rhs.serverPublicKey {return false}
    if lhs.culture != rhs.culture {return false}
    if lhs.country != rhs.country {return false}
    if lhs.ipAddress != rhs.ipAddress {return false}
    if lhs.isNewInstance != rhs.isNewInstance {return false}
    if lhs._membership != rhs._membership {return false}
    if lhs.currentAccountID != rhs.currentAccountID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
