// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: device/device_services.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ecliptix.proto.device.DeviceService

/// Namespace containing generated types for the "ecliptix.proto.device.DeviceService" service.
public enum Ecliptix_Proto_Device_DeviceService {
    /// Service descriptor for the "ecliptix.proto.device.DeviceService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.device.DeviceService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "RegisterDevice" metadata.
        public enum RegisterDevice {
            /// Request type for "RegisterDevice".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "RegisterDevice".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "RegisterDevice".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.device.DeviceService"),
                method: "RegisterDevice"
            )
        }
        /// Namespace for "EstablishSecureChannel" metadata.
        public enum EstablishSecureChannel {
            /// Request type for "EstablishSecureChannel".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "EstablishSecureChannel".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "EstablishSecureChannel".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.device.DeviceService"),
                method: "EstablishSecureChannel"
            )
        }
        /// Namespace for "RestoreSecureChannel" metadata.
        public enum RestoreSecureChannel {
            /// Request type for "RestoreSecureChannel".
            public typealias Input = Ecliptix_Proto_Device_RestoreChannelRequest
            /// Response type for "RestoreSecureChannel".
            public typealias Output = Ecliptix_Proto_Device_RestoreChannelResponse
            /// Descriptor for "RestoreSecureChannel".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.device.DeviceService"),
                method: "RestoreSecureChannel"
            )
        }
        /// Namespace for "AuthenticatedEstablishSecureChannel" metadata.
        public enum AuthenticatedEstablishSecureChannel {
            /// Request type for "AuthenticatedEstablishSecureChannel".
            public typealias Input = Ecliptix_Proto_Device_AuthenticatedEstablishRequest
            /// Response type for "AuthenticatedEstablishSecureChannel".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "AuthenticatedEstablishSecureChannel".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.device.DeviceService"),
                method: "AuthenticatedEstablishSecureChannel"
            )
        }
        /// Descriptors for all methods in the "ecliptix.proto.device.DeviceService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            RegisterDevice.descriptor,
            EstablishSecureChannel.descriptor,
            RestoreSecureChannel.descriptor,
            AuthenticatedEstablishSecureChannel.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ecliptix.proto.device.DeviceService" service.
    public static let ecliptix_proto_device_DeviceService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.device.DeviceService")
}

// MARK: ecliptix.proto.device.DeviceService (client)

extension Ecliptix_Proto_Device_DeviceService {
    /// Generated client protocol for the "ecliptix.proto.device.DeviceService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "RegisterDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func registerDevice<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "EstablishSecureChannel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func establishSecureChannel<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RestoreSecureChannel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Device_RestoreChannelRequest` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Device_RestoreChannelRequest` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Device_RestoreChannelResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func restoreSecureChannel<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Device_RestoreChannelRequest>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Device_RestoreChannelRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Device_RestoreChannelResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Device_RestoreChannelResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "AuthenticatedEstablishSecureChannel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Device_AuthenticatedEstablishRequest` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Device_AuthenticatedEstablishRequest` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func authenticatedEstablishSecureChannel<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Device_AuthenticatedEstablishRequest>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Device_AuthenticatedEstablishRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ecliptix.proto.device.DeviceService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "RegisterDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func registerDevice<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Device_DeviceService.Method.RegisterDevice.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "EstablishSecureChannel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func establishSecureChannel<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Device_DeviceService.Method.EstablishSecureChannel.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RestoreSecureChannel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Device_RestoreChannelRequest` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Device_RestoreChannelRequest` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Device_RestoreChannelResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func restoreSecureChannel<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Device_RestoreChannelRequest>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Device_RestoreChannelRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Device_RestoreChannelResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Device_RestoreChannelResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Device_DeviceService.Method.RestoreSecureChannel.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "AuthenticatedEstablishSecureChannel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Device_AuthenticatedEstablishRequest` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Device_AuthenticatedEstablishRequest` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func authenticatedEstablishSecureChannel<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Device_AuthenticatedEstablishRequest>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Device_AuthenticatedEstablishRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Device_DeviceService.Method.AuthenticatedEstablishSecureChannel.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Ecliptix_Proto_Device_DeviceService.ClientProtocol {
    /// Call the "RegisterDevice" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func registerDevice<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.registerDevice(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "EstablishSecureChannel" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func establishSecureChannel<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.establishSecureChannel(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RestoreSecureChannel" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Device_RestoreChannelRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func restoreSecureChannel<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Device_RestoreChannelRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Device_RestoreChannelResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.restoreSecureChannel(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Device_RestoreChannelRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Device_RestoreChannelResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AuthenticatedEstablishSecureChannel" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Device_AuthenticatedEstablishRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func authenticatedEstablishSecureChannel<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Device_AuthenticatedEstablishRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.authenticatedEstablishSecureChannel(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Device_AuthenticatedEstablishRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Ecliptix_Proto_Device_DeviceService.ClientProtocol {
    /// Call the "RegisterDevice" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func registerDevice<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.registerDevice(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "EstablishSecureChannel" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func establishSecureChannel<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.establishSecureChannel(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RestoreSecureChannel" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func restoreSecureChannel<Result>(
        _ message: Ecliptix_Proto_Device_RestoreChannelRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Device_RestoreChannelResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Device_RestoreChannelRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.restoreSecureChannel(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AuthenticatedEstablishSecureChannel" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func authenticatedEstablishSecureChannel<Result>(
        _ message: Ecliptix_Proto_Device_AuthenticatedEstablishRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Device_AuthenticatedEstablishRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.authenticatedEstablishSecureChannel(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}