// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: device/device_services.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Ecliptix_Proto_Device_RestoreChannelRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Ecliptix_Proto_Device_RestoreChannelResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: Ecliptix_Proto_Device_RestoreChannelResponse.Status = .sessionRestored

  public var receivingChainLength: UInt32 = 0

  public var sendingChainLength: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Status: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case sessionRestored // = 0
    case sessionNotFound // = 1
    case sessionExpired // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .sessionRestored
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .sessionRestored
      case 1: self = .sessionNotFound
      case 2: self = .sessionExpired
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .sessionRestored: return 0
      case .sessionNotFound: return 1
      case .sessionExpired: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Ecliptix_Proto_Device_RestoreChannelResponse.Status] = [
      .sessionRestored,
      .sessionNotFound,
      .sessionExpired,
    ]

  }

  public init() {}
}

public struct Ecliptix_Proto_Device_AuthenticatedEstablishRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var membershipUniqueID: Data = Data()

  public var clientPubKeyExchange: Ecliptix_Proto_Protocol_PubKeyExchange {
    get {return _clientPubKeyExchange ?? Ecliptix_Proto_Protocol_PubKeyExchange()}
    set {_clientPubKeyExchange = newValue}
  }
  /// Returns true if `clientPubKeyExchange` has been explicitly set.
  public var hasClientPubKeyExchange: Bool {return self._clientPubKeyExchange != nil}
  /// Clears the value of `clientPubKeyExchange`. Subsequent reads from it will return its default value.
  public mutating func clearClientPubKeyExchange() {self._clientPubKeyExchange = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _clientPubKeyExchange: Ecliptix_Proto_Protocol_PubKeyExchange? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "ecliptix.proto.device"

extension Ecliptix_Proto_Device_RestoreChannelRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RestoreChannelRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Device_RestoreChannelRequest, rhs: Ecliptix_Proto_Device_RestoreChannelRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Device_RestoreChannelResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RestoreChannelResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "status"),
    2: .standard(proto: "receiving_chain_length"),
    3: .standard(proto: "sending_chain_length"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.receivingChainLength) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.sendingChainLength) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != .sessionRestored {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if self.receivingChainLength != 0 {
      try visitor.visitSingularUInt32Field(value: self.receivingChainLength, fieldNumber: 2)
    }
    if self.sendingChainLength != 0 {
      try visitor.visitSingularUInt32Field(value: self.sendingChainLength, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Device_RestoreChannelResponse, rhs: Ecliptix_Proto_Device_RestoreChannelResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.receivingChainLength != rhs.receivingChainLength {return false}
    if lhs.sendingChainLength != rhs.sendingChainLength {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Device_RestoreChannelResponse.Status: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SESSION_RESTORED"),
    1: .same(proto: "SESSION_NOT_FOUND"),
    2: .same(proto: "SESSION_EXPIRED"),
  ]
}

extension Ecliptix_Proto_Device_AuthenticatedEstablishRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AuthenticatedEstablishRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "membership_unique_id"),
    2: .standard(proto: "client_pub_key_exchange"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.membershipUniqueID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._clientPubKeyExchange) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.membershipUniqueID.isEmpty {
      try visitor.visitSingularBytesField(value: self.membershipUniqueID, fieldNumber: 1)
    }
    try { if let v = self._clientPubKeyExchange {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Device_AuthenticatedEstablishRequest, rhs: Ecliptix_Proto_Device_AuthenticatedEstablishRequest) -> Bool {
    if lhs.membershipUniqueID != rhs.membershipUniqueID {return false}
    if lhs._clientPubKeyExchange != rhs._clientPubKeyExchange {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
