// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: common/encryption.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Ecliptix_Proto_Common_KeyMaterials: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var identityPublicKey: Data = Data()

  public var ephemeralPublicKey: Data = Data()

  public var oneTimePreKey: Data = Data()

  public var signature: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "ecliptix.proto.common"

extension Ecliptix_Proto_Common_KeyMaterials: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeyMaterials"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "identity_public_key"),
    2: .standard(proto: "ephemeral_public_key"),
    3: .standard(proto: "one_time_pre_key"),
    4: .same(proto: "signature"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.identityPublicKey) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.ephemeralPublicKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.oneTimePreKey) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.identityPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.identityPublicKey, fieldNumber: 1)
    }
    if !self.ephemeralPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ephemeralPublicKey, fieldNumber: 2)
    }
    if !self.oneTimePreKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.oneTimePreKey, fieldNumber: 3)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Common_KeyMaterials, rhs: Ecliptix_Proto_Common_KeyMaterials) -> Bool {
    if lhs.identityPublicKey != rhs.identityPublicKey {return false}
    if lhs.ephemeralPublicKey != rhs.ephemeralPublicKey {return false}
    if lhs.oneTimePreKey != rhs.oneTimePreKey {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
