// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: common/health_check.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ecliptix.proto.HealthCheck

/// Namespace containing generated types for the "ecliptix.proto.HealthCheck" service.
public enum Ecliptix_Proto_HealthCheck {
    /// Service descriptor for the "ecliptix.proto.HealthCheck" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.HealthCheck")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "SayHello" metadata.
        public enum SayHello {
            /// Request type for "SayHello".
            public typealias Input = Ecliptix_Proto_HelloRequest
            /// Response type for "SayHello".
            public typealias Output = Ecliptix_Proto_HelloReply
            /// Descriptor for "SayHello".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.HealthCheck"),
                method: "SayHello"
            )
        }
        /// Descriptors for all methods in the "ecliptix.proto.HealthCheck" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SayHello.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ecliptix.proto.HealthCheck" service.
    public static let ecliptix_proto_HealthCheck = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.HealthCheck")
}

// MARK: ecliptix.proto.HealthCheck (client)

extension Ecliptix_Proto_HealthCheck {
    /// Generated client protocol for the "ecliptix.proto.HealthCheck" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "SayHello" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_HelloRequest` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_HelloRequest` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_HelloReply` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func sayHello<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_HelloRequest>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_HelloRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_HelloReply>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_HelloReply>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ecliptix.proto.HealthCheck" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "SayHello" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_HelloRequest` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_HelloRequest` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_HelloReply` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func sayHello<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_HelloRequest>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_HelloRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_HelloReply>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_HelloReply>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_HealthCheck.Method.SayHello.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Ecliptix_Proto_HealthCheck.ClientProtocol {
    /// Call the "SayHello" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_HelloRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sayHello<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_HelloRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_HelloReply>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.sayHello(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_HelloRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_HelloReply>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Ecliptix_Proto_HealthCheck.ClientProtocol {
    /// Call the "SayHello" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func sayHello<Result>(
        _ message: Ecliptix_Proto_HelloRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_HelloReply>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_HelloRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.sayHello(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}