// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: membership/membership_services.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ecliptix.proto.membership.MembershipServices

/// Namespace containing generated types for the "ecliptix.proto.membership.MembershipServices" service.
public enum Ecliptix_Proto_Membership_MembershipServices {
    /// Service descriptor for the "ecliptix.proto.membership.MembershipServices" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "OpaqueRegistrationInitRequest" metadata.
        public enum OpaqueRegistrationInitRequest {
            /// Request type for "OpaqueRegistrationInitRequest".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "OpaqueRegistrationInitRequest".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "OpaqueRegistrationInitRequest".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "OpaqueRegistrationInitRequest"
            )
        }
        /// Namespace for "OpaqueRegistrationCompleteRequest" metadata.
        public enum OpaqueRegistrationCompleteRequest {
            /// Request type for "OpaqueRegistrationCompleteRequest".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "OpaqueRegistrationCompleteRequest".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "OpaqueRegistrationCompleteRequest".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "OpaqueRegistrationCompleteRequest"
            )
        }
        /// Namespace for "OpaqueRecoverySecretKeyInitRequest" metadata.
        public enum OpaqueRecoverySecretKeyInitRequest {
            /// Request type for "OpaqueRecoverySecretKeyInitRequest".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "OpaqueRecoverySecretKeyInitRequest".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "OpaqueRecoverySecretKeyInitRequest".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "OpaqueRecoverySecretKeyInitRequest"
            )
        }
        /// Namespace for "OpaqueRecoverySecretKeyCompleteRequest" metadata.
        public enum OpaqueRecoverySecretKeyCompleteRequest {
            /// Request type for "OpaqueRecoverySecretKeyCompleteRequest".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "OpaqueRecoverySecretKeyCompleteRequest".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "OpaqueRecoverySecretKeyCompleteRequest".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "OpaqueRecoverySecretKeyCompleteRequest"
            )
        }
        /// Namespace for "OpaqueSignInInitRequest" metadata.
        public enum OpaqueSignInInitRequest {
            /// Request type for "OpaqueSignInInitRequest".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "OpaqueSignInInitRequest".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "OpaqueSignInInitRequest".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "OpaqueSignInInitRequest"
            )
        }
        /// Namespace for "OpaqueSignInCompleteRequest" metadata.
        public enum OpaqueSignInCompleteRequest {
            /// Request type for "OpaqueSignInCompleteRequest".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "OpaqueSignInCompleteRequest".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "OpaqueSignInCompleteRequest".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "OpaqueSignInCompleteRequest"
            )
        }
        /// Namespace for "Logout" metadata.
        public enum Logout {
            /// Request type for "Logout".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "Logout".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "Logout".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "Logout"
            )
        }
        /// Namespace for "AnonymousLogout" metadata.
        public enum AnonymousLogout {
            /// Request type for "AnonymousLogout".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "AnonymousLogout".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "AnonymousLogout".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "AnonymousLogout"
            )
        }
        /// Namespace for "GetLogoutHistory" metadata.
        public enum GetLogoutHistory {
            /// Request type for "GetLogoutHistory".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "GetLogoutHistory".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "GetLogoutHistory".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices"),
                method: "GetLogoutHistory"
            )
        }
        /// Descriptors for all methods in the "ecliptix.proto.membership.MembershipServices" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            OpaqueRegistrationInitRequest.descriptor,
            OpaqueRegistrationCompleteRequest.descriptor,
            OpaqueRecoverySecretKeyInitRequest.descriptor,
            OpaqueRecoverySecretKeyCompleteRequest.descriptor,
            OpaqueSignInInitRequest.descriptor,
            OpaqueSignInCompleteRequest.descriptor,
            Logout.descriptor,
            AnonymousLogout.descriptor,
            GetLogoutHistory.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ecliptix.proto.membership.MembershipServices" service.
    public static let ecliptix_proto_membership_MembershipServices = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.MembershipServices")
}

// MARK: ecliptix.proto.membership.MembershipServices (client)

extension Ecliptix_Proto_Membership_MembershipServices {
    /// Generated client protocol for the "ecliptix.proto.membership.MembershipServices" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "OpaqueRegistrationInitRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func opaqueRegistrationInitRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "OpaqueRegistrationCompleteRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func opaqueRegistrationCompleteRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "OpaqueRecoverySecretKeyInitRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func opaqueRecoverySecretKeyInitRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "OpaqueRecoverySecretKeyCompleteRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func opaqueRecoverySecretKeyCompleteRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "OpaqueSignInInitRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func opaqueSignInInitRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "OpaqueSignInCompleteRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func opaqueSignInCompleteRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Logout" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func logout<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "AnonymousLogout" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func anonymousLogout<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetLogoutHistory" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getLogoutHistory<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ecliptix.proto.membership.MembershipServices" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "OpaqueRegistrationInitRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func opaqueRegistrationInitRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.OpaqueRegistrationInitRequest.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "OpaqueRegistrationCompleteRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func opaqueRegistrationCompleteRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.OpaqueRegistrationCompleteRequest.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "OpaqueRecoverySecretKeyInitRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func opaqueRecoverySecretKeyInitRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.OpaqueRecoverySecretKeyInitRequest.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "OpaqueRecoverySecretKeyCompleteRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func opaqueRecoverySecretKeyCompleteRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.OpaqueRecoverySecretKeyCompleteRequest.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "OpaqueSignInInitRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func opaqueSignInInitRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.OpaqueSignInInitRequest.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "OpaqueSignInCompleteRequest" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func opaqueSignInCompleteRequest<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.OpaqueSignInCompleteRequest.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Logout" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func logout<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.Logout.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "AnonymousLogout" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func anonymousLogout<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.AnonymousLogout.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetLogoutHistory" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getLogoutHistory<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_MembershipServices.Method.GetLogoutHistory.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Ecliptix_Proto_Membership_MembershipServices.ClientProtocol {
    /// Call the "OpaqueRegistrationInitRequest" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueRegistrationInitRequest<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.opaqueRegistrationInitRequest(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueRegistrationCompleteRequest" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueRegistrationCompleteRequest<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.opaqueRegistrationCompleteRequest(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueRecoverySecretKeyInitRequest" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueRecoverySecretKeyInitRequest<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.opaqueRecoverySecretKeyInitRequest(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueRecoverySecretKeyCompleteRequest" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueRecoverySecretKeyCompleteRequest<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.opaqueRecoverySecretKeyCompleteRequest(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueSignInInitRequest" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueSignInInitRequest<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.opaqueSignInInitRequest(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueSignInCompleteRequest" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueSignInCompleteRequest<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.opaqueSignInCompleteRequest(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Logout" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func logout<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.logout(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AnonymousLogout" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func anonymousLogout<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.anonymousLogout(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetLogoutHistory" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getLogoutHistory<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getLogoutHistory(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Ecliptix_Proto_Membership_MembershipServices.ClientProtocol {
    /// Call the "OpaqueRegistrationInitRequest" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueRegistrationInitRequest<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.opaqueRegistrationInitRequest(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueRegistrationCompleteRequest" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueRegistrationCompleteRequest<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.opaqueRegistrationCompleteRequest(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueRecoverySecretKeyInitRequest" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueRecoverySecretKeyInitRequest<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.opaqueRecoverySecretKeyInitRequest(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueRecoverySecretKeyCompleteRequest" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueRecoverySecretKeyCompleteRequest<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.opaqueRecoverySecretKeyCompleteRequest(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueSignInInitRequest" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueSignInInitRequest<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.opaqueSignInInitRequest(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "OpaqueSignInCompleteRequest" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func opaqueSignInCompleteRequest<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.opaqueSignInCompleteRequest(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Logout" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func logout<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.logout(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "AnonymousLogout" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func anonymousLogout<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.anonymousLogout(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetLogoutHistory" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getLogoutHistory<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.getLogoutHistory(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}