// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: membership/membership_core.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Ecliptix_Proto_Membership_LogoutScope: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case thisDevice // = 0
  case allDevices // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .thisDevice
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .thisDevice
    case 1: self = .allDevices
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .thisDevice: return 0
    case .allDevices: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ecliptix_Proto_Membership_LogoutScope] = [
    .thisDevice,
    .allDevices,
  ]

}

public struct Ecliptix_Proto_Membership_Membership: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uniqueIdentifier: Data = Data()

  public var status: Ecliptix_Proto_Membership_Membership.ActivityStatus = .active

  public var creationStatus: Ecliptix_Proto_Membership_Membership.CreationStatus {
    get {return _creationStatus ?? .otpVerified}
    set {_creationStatus = newValue}
  }
  /// Returns true if `creationStatus` has been explicitly set.
  public var hasCreationStatus: Bool {return self._creationStatus != nil}
  /// Clears the value of `creationStatus`. Subsequent reads from it will return its default value.
  public mutating func clearCreationStatus() {self._creationStatus = nil}

  public var accountUniqueIdentifier: Data {
    get {return _accountUniqueIdentifier ?? Data()}
    set {_accountUniqueIdentifier = newValue}
  }
  /// Returns true if `accountUniqueIdentifier` has been explicitly set.
  public var hasAccountUniqueIdentifier: Bool {return self._accountUniqueIdentifier != nil}
  /// Clears the value of `accountUniqueIdentifier`. Subsequent reads from it will return its default value.
  public mutating func clearAccountUniqueIdentifier() {self._accountUniqueIdentifier = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum ActivityStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case active // = 0
    case inactive // = 1
    case UNRECOGNIZED(Int)

    public init() {
      self = .active
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .active
      case 1: self = .inactive
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .active: return 0
      case .inactive: return 1
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Ecliptix_Proto_Membership_Membership.ActivityStatus] = [
      .active,
      .inactive,
    ]

  }

  public enum CreationStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case otpVerified // = 0
    case secureKeySet // = 1
    case passphraseSet // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .otpVerified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .otpVerified
      case 1: self = .secureKeySet
      case 2: self = .passphraseSet
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .otpVerified: return 0
      case .secureKeySet: return 1
      case .passphraseSet: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Ecliptix_Proto_Membership_Membership.CreationStatus] = [
      .otpVerified,
      .secureKeySet,
      .passphraseSet,
    ]

  }

  public init() {}

  fileprivate var _creationStatus: Ecliptix_Proto_Membership_Membership.CreationStatus? = nil
  fileprivate var _accountUniqueIdentifier: Data? = nil
}

public struct Ecliptix_Proto_Membership_LogoutRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var membershipIdentifier: Data = Data()

  public var logoutReason: String = String()

  public var timestamp: Int64 = 0

  public var hmacProof: Data = Data()

  public var scope: Ecliptix_Proto_Membership_LogoutScope = .thisDevice

  public var accountIdentifier: Data {
    get {return _accountIdentifier ?? Data()}
    set {_accountIdentifier = newValue}
  }
  /// Returns true if `accountIdentifier` has been explicitly set.
  public var hasAccountIdentifier: Bool {return self._accountIdentifier != nil}
  /// Clears the value of `accountIdentifier`. Subsequent reads from it will return its default value.
  public mutating func clearAccountIdentifier() {self._accountIdentifier = nil}

  public var deviceIdentifier: Data {
    get {return _deviceIdentifier ?? Data()}
    set {_deviceIdentifier = newValue}
  }
  /// Returns true if `deviceIdentifier` has been explicitly set.
  public var hasDeviceIdentifier: Bool {return self._deviceIdentifier != nil}
  /// Clears the value of `deviceIdentifier`. Subsequent reads from it will return its default value.
  public mutating func clearDeviceIdentifier() {self._deviceIdentifier = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _accountIdentifier: Data? = nil
  fileprivate var _deviceIdentifier: Data? = nil
}

public struct Ecliptix_Proto_Membership_LogoutResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var result: Ecliptix_Proto_Membership_LogoutResponse.Result = .succeeded

  public var serverTimestamp: Int64 = 0

  public var revocationProof: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Result: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case succeeded // = 0
    case alreadyLoggedOut // = 1
    case sessionNotFound // = 2
    case failed // = 3
    case invalidTimestamp // = 4
    case invalidHmac // = 5
    case UNRECOGNIZED(Int)

    public init() {
      self = .succeeded
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .succeeded
      case 1: self = .alreadyLoggedOut
      case 2: self = .sessionNotFound
      case 3: self = .failed
      case 4: self = .invalidTimestamp
      case 5: self = .invalidHmac
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .succeeded: return 0
      case .alreadyLoggedOut: return 1
      case .sessionNotFound: return 2
      case .failed: return 3
      case .invalidTimestamp: return 4
      case .invalidHmac: return 5
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Ecliptix_Proto_Membership_LogoutResponse.Result] = [
      .succeeded,
      .alreadyLoggedOut,
      .sessionNotFound,
      .failed,
      .invalidTimestamp,
      .invalidHmac,
    ]

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "ecliptix.proto.membership"

extension Ecliptix_Proto_Membership_LogoutScope: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "THIS_DEVICE"),
    1: .same(proto: "ALL_DEVICES"),
  ]
}

extension Ecliptix_Proto_Membership_Membership: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Membership"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "unique_identifier"),
    3: .same(proto: "status"),
    4: .standard(proto: "creation_status"),
    5: .standard(proto: "account_unique_identifier"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.uniqueIdentifier) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._creationStatus) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self._accountUniqueIdentifier) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.uniqueIdentifier.isEmpty {
      try visitor.visitSingularBytesField(value: self.uniqueIdentifier, fieldNumber: 1)
    }
    if self.status != .active {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 3)
    }
    try { if let v = self._creationStatus {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._accountUniqueIdentifier {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Membership_Membership, rhs: Ecliptix_Proto_Membership_Membership) -> Bool {
    if lhs.uniqueIdentifier != rhs.uniqueIdentifier {return false}
    if lhs.status != rhs.status {return false}
    if lhs._creationStatus != rhs._creationStatus {return false}
    if lhs._accountUniqueIdentifier != rhs._accountUniqueIdentifier {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Membership_Membership.ActivityStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ACTIVE"),
    1: .same(proto: "INACTIVE"),
  ]
}

extension Ecliptix_Proto_Membership_Membership.CreationStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "OTP_VERIFIED"),
    1: .same(proto: "SECURE_KEY_SET"),
    2: .same(proto: "PASSPHRASE_SET"),
  ]
}

extension Ecliptix_Proto_Membership_LogoutRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LogoutRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "membership_identifier"),
    2: .standard(proto: "logout_reason"),
    3: .same(proto: "timestamp"),
    4: .standard(proto: "hmac_proof"),
    5: .same(proto: "scope"),
    6: .standard(proto: "account_identifier"),
    7: .standard(proto: "device_identifier"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.membershipIdentifier) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.logoutReason) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.timestamp) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.hmacProof) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.scope) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self._accountIdentifier) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self._deviceIdentifier) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.membershipIdentifier.isEmpty {
      try visitor.visitSingularBytesField(value: self.membershipIdentifier, fieldNumber: 1)
    }
    if !self.logoutReason.isEmpty {
      try visitor.visitSingularStringField(value: self.logoutReason, fieldNumber: 2)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.timestamp, fieldNumber: 3)
    }
    if !self.hmacProof.isEmpty {
      try visitor.visitSingularBytesField(value: self.hmacProof, fieldNumber: 4)
    }
    if self.scope != .thisDevice {
      try visitor.visitSingularEnumField(value: self.scope, fieldNumber: 5)
    }
    try { if let v = self._accountIdentifier {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._deviceIdentifier {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Membership_LogoutRequest, rhs: Ecliptix_Proto_Membership_LogoutRequest) -> Bool {
    if lhs.membershipIdentifier != rhs.membershipIdentifier {return false}
    if lhs.logoutReason != rhs.logoutReason {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.hmacProof != rhs.hmacProof {return false}
    if lhs.scope != rhs.scope {return false}
    if lhs._accountIdentifier != rhs._accountIdentifier {return false}
    if lhs._deviceIdentifier != rhs._deviceIdentifier {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Membership_LogoutResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LogoutResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "result"),
    2: .standard(proto: "server_timestamp"),
    3: .standard(proto: "revocation_proof"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.result) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.serverTimestamp) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.revocationProof) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.result != .succeeded {
      try visitor.visitSingularEnumField(value: self.result, fieldNumber: 1)
    }
    if self.serverTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.serverTimestamp, fieldNumber: 2)
    }
    if !self.revocationProof.isEmpty {
      try visitor.visitSingularBytesField(value: self.revocationProof, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Membership_LogoutResponse, rhs: Ecliptix_Proto_Membership_LogoutResponse) -> Bool {
    if lhs.result != rhs.result {return false}
    if lhs.serverTimestamp != rhs.serverTimestamp {return false}
    if lhs.revocationProof != rhs.revocationProof {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Membership_LogoutResponse.Result: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "SUCCEEDED"),
    1: .same(proto: "ALREADY_LOGGED_OUT"),
    2: .same(proto: "SESSION_NOT_FOUND"),
    3: .same(proto: "FAILED"),
    4: .same(proto: "INVALID_TIMESTAMP"),
    5: .same(proto: "INVALID_HMAC"),
  ]
}
