name: EcliptixApp
options:
  bundleIdPrefix: com.ecliptix
  deploymentTarget:
    iOS: "18.0"
  createIntermediateGroups: true

packages:
  EcliptixWorkspace:
    path: ../

targets:
  EcliptixApp:
    type: application
    platform: iOS
    deploymentTarget: "18.0"

    sources:
      - path: EcliptixApp
        excludes:
          - "**/.DS_Store"

    preBuildScripts:
      - name: Generate Protobuf Files
        script: |
          set -e
          echo "Running protobuf generation..."
          cd "${PROJECT_DIR}/.."
          bash scripts/generate_protos.sh
        inputFiles:
          - $(PROJECT_DIR)/../Protobufs/Sources/account/account_models.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/authentication/auth_services.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/authentication/verification_models.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/common/encryption.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/common/health_check.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/common/secure_envelope.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/common/types.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/device/application_settings.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/device/device_models.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/device/device_services.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/membership/membership_core.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/membership/membership_services.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/membership/opaque_models.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/protocol/key_exchange.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/protocol/key_materials.proto
          - $(PROJECT_DIR)/../Protobufs/Sources/protocol/protocol_state.proto
        outputFiles:
          - $(PROJECT_DIR)/../Protobufs/Generated
        basedOnDependencyAnalysis: true

    dependencies:
      - package: EcliptixWorkspace
        product: EcliptixCore
      - package: EcliptixWorkspace
        product: EcliptixNetworking
      - package: EcliptixWorkspace
        product: EcliptixSecurity
      - package: EcliptixWorkspace
        product: EcliptixAuthentication
      - package: EcliptixWorkspace
        product: EcliptixProto

    settings:
      base:
        PRODUCT_NAME: EcliptixApp
        PRODUCT_BUNDLE_IDENTIFIER: com.ecliptix.app
        INFOPLIST_FILE: EcliptixApp/Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_OPTIMIZATION_LEVEL: -Onone
        ENABLE_PREVIEWS: true
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_USER_SCRIPT_SANDBOXING: false
        OTHER_SWIFT_FLAGS: "-Xfrontend -warn-long-function-bodies=100 -Xfrontend -warn-long-expression-type-checking=100"

      debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG

      release:
        SWIFT_OPTIMIZATION_LEVEL: -O

schemes:
  EcliptixApp:
    build:
      targets:
        EcliptixApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
