// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: account/account_models.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Ecliptix_Proto_Account_AccountType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case personal // = 0
  case military // = 1
  case business // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .personal
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .personal
    case 1: self = .military
    case 2: self = .business
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .personal: return 0
    case .military: return 1
    case .business: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ecliptix_Proto_Account_AccountType] = [
    .personal,
    .military,
    .business,
  ]

}

public enum Ecliptix_Proto_Account_AccountStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case inactive // = 0
  case active // = 1
  case suspended // = 2
  case locked // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .inactive
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .inactive
    case 1: self = .active
    case 2: self = .suspended
    case 3: self = .locked
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .inactive: return 0
    case .active: return 1
    case .suspended: return 2
    case .locked: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ecliptix_Proto_Account_AccountStatus] = [
    .inactive,
    .active,
    .suspended,
    .locked,
  ]

}

public struct Ecliptix_Proto_Account_Account: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uniqueIdentifier: Data = Data()

  public var membershipIdentifier: Data = Data()

  public var accountType: Ecliptix_Proto_Account_AccountType = .personal

  public var accountName: String = String()

  public var status: Ecliptix_Proto_Account_AccountStatus = .inactive

  public var isDefaultAccount: Bool = false

  public var preferredLanguage: String {
    get {return _preferredLanguage ?? String()}
    set {_preferredLanguage = newValue}
  }
  /// Returns true if `preferredLanguage` has been explicitly set.
  public var hasPreferredLanguage: Bool {return self._preferredLanguage != nil}
  /// Clears the value of `preferredLanguage`. Subsequent reads from it will return its default value.
  public mutating func clearPreferredLanguage() {self._preferredLanguage = nil}

  public var timeZoneID: String {
    get {return _timeZoneID ?? String()}
    set {_timeZoneID = newValue}
  }
  /// Returns true if `timeZoneID` has been explicitly set.
  public var hasTimeZoneID: Bool {return self._timeZoneID != nil}
  /// Clears the value of `timeZoneID`. Subsequent reads from it will return its default value.
  public mutating func clearTimeZoneID() {self._timeZoneID = nil}

  public var region: String {
    get {return _region ?? String()}
    set {_region = newValue}
  }
  /// Returns true if `region` has been explicitly set.
  public var hasRegion: Bool {return self._region != nil}
  /// Clears the value of `region`. Subsequent reads from it will return its default value.
  public mutating func clearRegion() {self._region = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _preferredLanguage: String? = nil
  fileprivate var _timeZoneID: String? = nil
  fileprivate var _region: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "ecliptix.proto.account"

extension Ecliptix_Proto_Account_AccountType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PERSONAL"),
    1: .same(proto: "MILITARY"),
    2: .same(proto: "BUSINESS"),
  ]
}

extension Ecliptix_Proto_Account_AccountStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "INACTIVE"),
    1: .same(proto: "ACTIVE"),
    2: .same(proto: "SUSPENDED"),
    3: .same(proto: "LOCKED"),
  ]
}

extension Ecliptix_Proto_Account_Account: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Account"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "unique_identifier"),
    2: .standard(proto: "membership_identifier"),
    3: .standard(proto: "account_type"),
    4: .standard(proto: "account_name"),
    5: .same(proto: "status"),
    6: .standard(proto: "is_default_account"),
    7: .standard(proto: "preferred_language"),
    8: .standard(proto: "time_zone_id"),
    9: .same(proto: "region"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.uniqueIdentifier) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.membershipIdentifier) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.accountType) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.accountName) }()
      case 5: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.isDefaultAccount) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._preferredLanguage) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._timeZoneID) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self._region) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.uniqueIdentifier.isEmpty {
      try visitor.visitSingularBytesField(value: self.uniqueIdentifier, fieldNumber: 1)
    }
    if !self.membershipIdentifier.isEmpty {
      try visitor.visitSingularBytesField(value: self.membershipIdentifier, fieldNumber: 2)
    }
    if self.accountType != .personal {
      try visitor.visitSingularEnumField(value: self.accountType, fieldNumber: 3)
    }
    if !self.accountName.isEmpty {
      try visitor.visitSingularStringField(value: self.accountName, fieldNumber: 4)
    }
    if self.status != .inactive {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 5)
    }
    if self.isDefaultAccount != false {
      try visitor.visitSingularBoolField(value: self.isDefaultAccount, fieldNumber: 6)
    }
    try { if let v = self._preferredLanguage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._timeZoneID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._region {
      try visitor.visitSingularStringField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Account_Account, rhs: Ecliptix_Proto_Account_Account) -> Bool {
    if lhs.uniqueIdentifier != rhs.uniqueIdentifier {return false}
    if lhs.membershipIdentifier != rhs.membershipIdentifier {return false}
    if lhs.accountType != rhs.accountType {return false}
    if lhs.accountName != rhs.accountName {return false}
    if lhs.status != rhs.status {return false}
    if lhs.isDefaultAccount != rhs.isDefaultAccount {return false}
    if lhs._preferredLanguage != rhs._preferredLanguage {return false}
    if lhs._timeZoneID != rhs._timeZoneID {return false}
    if lhs._region != rhs._region {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
