// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: authentication/auth_services.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - ecliptix.proto.membership.AuthVerificationServices

/// Namespace containing generated types for the "ecliptix.proto.membership.AuthVerificationServices" service.
public enum Ecliptix_Proto_Membership_AuthVerificationServices {
    /// Service descriptor for the "ecliptix.proto.membership.AuthVerificationServices" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.AuthVerificationServices")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "InitiateVerification" metadata.
        public enum InitiateVerification {
            /// Request type for "InitiateVerification".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "InitiateVerification".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "InitiateVerification".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.AuthVerificationServices"),
                method: "InitiateVerification"
            )
        }
        /// Namespace for "VerifyOtp" metadata.
        public enum VerifyOtp {
            /// Request type for "VerifyOtp".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "VerifyOtp".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "VerifyOtp".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.AuthVerificationServices"),
                method: "VerifyOtp"
            )
        }
        /// Namespace for "ValidateMobileNumber" metadata.
        public enum ValidateMobileNumber {
            /// Request type for "ValidateMobileNumber".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "ValidateMobileNumber".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "ValidateMobileNumber".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.AuthVerificationServices"),
                method: "ValidateMobileNumber"
            )
        }
        /// Namespace for "RecoverySecretKeyMobileVerification" metadata.
        public enum RecoverySecretKeyMobileVerification {
            /// Request type for "RecoverySecretKeyMobileVerification".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "RecoverySecretKeyMobileVerification".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "RecoverySecretKeyMobileVerification".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.AuthVerificationServices"),
                method: "RecoverySecretKeyMobileVerification"
            )
        }
        /// Namespace for "CheckMobileNumberAvailability" metadata.
        public enum CheckMobileNumberAvailability {
            /// Request type for "CheckMobileNumberAvailability".
            public typealias Input = Ecliptix_Proto_Common_SecureEnvelope
            /// Response type for "CheckMobileNumberAvailability".
            public typealias Output = Ecliptix_Proto_Common_SecureEnvelope
            /// Descriptor for "CheckMobileNumberAvailability".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.AuthVerificationServices"),
                method: "CheckMobileNumberAvailability"
            )
        }
        /// Descriptors for all methods in the "ecliptix.proto.membership.AuthVerificationServices" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            InitiateVerification.descriptor,
            VerifyOtp.descriptor,
            ValidateMobileNumber.descriptor,
            RecoverySecretKeyMobileVerification.descriptor,
            CheckMobileNumberAvailability.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "ecliptix.proto.membership.AuthVerificationServices" service.
    public static let ecliptix_proto_membership_AuthVerificationServices = GRPCCore.ServiceDescriptor(fullyQualifiedService: "ecliptix.proto.membership.AuthVerificationServices")
}

// MARK: ecliptix.proto.membership.AuthVerificationServices (client)

extension Ecliptix_Proto_Membership_AuthVerificationServices {
    /// Generated client protocol for the "ecliptix.proto.membership.AuthVerificationServices" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "InitiateVerification" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func initiateVerification<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "VerifyOtp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func verifyOtp<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ValidateMobileNumber" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func validateMobileNumber<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RecoverySecretKeyMobileVerification" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func recoverySecretKeyMobileVerification<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "CheckMobileNumberAvailability" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func checkMobileNumberAvailability<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "ecliptix.proto.membership.AuthVerificationServices" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "InitiateVerification" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func initiateVerification<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Ecliptix_Proto_Membership_AuthVerificationServices.Method.InitiateVerification.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "VerifyOtp" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func verifyOtp<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_AuthVerificationServices.Method.VerifyOtp.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ValidateMobileNumber" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func validateMobileNumber<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_AuthVerificationServices.Method.ValidateMobileNumber.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RecoverySecretKeyMobileVerification" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func recoverySecretKeyMobileVerification<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_AuthVerificationServices.Method.RecoverySecretKeyMobileVerification.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "CheckMobileNumberAvailability" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
        ///   - serializer: A serializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - deserializer: A deserializer for `Ecliptix_Proto_Common_SecureEnvelope` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func checkMobileNumberAvailability<Result>(
            request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
            serializer: some GRPCCore.MessageSerializer<Ecliptix_Proto_Common_SecureEnvelope>,
            deserializer: some GRPCCore.MessageDeserializer<Ecliptix_Proto_Common_SecureEnvelope>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Ecliptix_Proto_Membership_AuthVerificationServices.Method.CheckMobileNumberAvailability.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Ecliptix_Proto_Membership_AuthVerificationServices.ClientProtocol {
    /// Call the "InitiateVerification" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func initiateVerification<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.initiateVerification(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "VerifyOtp" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func verifyOtp<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.verifyOtp(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ValidateMobileNumber" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func validateMobileNumber<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.validateMobileNumber(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RecoverySecretKeyMobileVerification" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func recoverySecretKeyMobileVerification<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.recoverySecretKeyMobileVerification(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CheckMobileNumberAvailability" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Ecliptix_Proto_Common_SecureEnvelope` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func checkMobileNumberAvailability<Result>(
        request: GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.checkMobileNumberAvailability(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Ecliptix_Proto_Common_SecureEnvelope>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Ecliptix_Proto_Membership_AuthVerificationServices.ClientProtocol {
    /// Call the "InitiateVerification" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func initiateVerification<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.initiateVerification(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "VerifyOtp" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func verifyOtp<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.verifyOtp(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ValidateMobileNumber" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func validateMobileNumber<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.validateMobileNumber(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RecoverySecretKeyMobileVerification" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func recoverySecretKeyMobileVerification<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.recoverySecretKeyMobileVerification(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "CheckMobileNumberAvailability" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func checkMobileNumberAvailability<Result>(
        _ message: Ecliptix_Proto_Common_SecureEnvelope,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Ecliptix_Proto_Common_SecureEnvelope>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Ecliptix_Proto_Common_SecureEnvelope>(
            message: message,
            metadata: metadata
        )
        return try await self.checkMobileNumberAvailability(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}