// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: protocol/protocol_state.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Ecliptix_Proto_Protocol_LoadLevel: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case light // = 0
  case moderate // = 1
  case heavy // = 2
  case extreme // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .light
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .light
    case 1: self = .moderate
    case 2: self = .heavy
    case 3: self = .extreme
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .light: return 0
    case .moderate: return 1
    case .heavy: return 2
    case .extreme: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Ecliptix_Proto_Protocol_LoadLevel] = [
    .light,
    .moderate,
    .heavy,
    .extreme,
  ]

}

public struct Ecliptix_Proto_Protocol_EcliptixSessionState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var connectID: UInt32 {
    get {return _storage._connectID}
    set {_uniqueStorage()._connectID = newValue}
  }

  public var identityKeys: Ecliptix_Proto_Protocol_IdentityKeysState {
    get {return _storage._identityKeys ?? Ecliptix_Proto_Protocol_IdentityKeysState()}
    set {_uniqueStorage()._identityKeys = newValue}
  }
  /// Returns true if `identityKeys` has been explicitly set.
  public var hasIdentityKeys: Bool {return _storage._identityKeys != nil}
  /// Clears the value of `identityKeys`. Subsequent reads from it will return its default value.
  public mutating func clearIdentityKeys() {_uniqueStorage()._identityKeys = nil}

  public var peerHandshakeMessage: Ecliptix_Proto_Protocol_PubKeyExchange {
    get {return _storage._peerHandshakeMessage ?? Ecliptix_Proto_Protocol_PubKeyExchange()}
    set {_uniqueStorage()._peerHandshakeMessage = newValue}
  }
  /// Returns true if `peerHandshakeMessage` has been explicitly set.
  public var hasPeerHandshakeMessage: Bool {return _storage._peerHandshakeMessage != nil}
  /// Clears the value of `peerHandshakeMessage`. Subsequent reads from it will return its default value.
  public mutating func clearPeerHandshakeMessage() {_uniqueStorage()._peerHandshakeMessage = nil}

  public var ratchetState: Ecliptix_Proto_Protocol_RatchetState {
    get {return _storage._ratchetState ?? Ecliptix_Proto_Protocol_RatchetState()}
    set {_uniqueStorage()._ratchetState = newValue}
  }
  /// Returns true if `ratchetState` has been explicitly set.
  public var hasRatchetState: Bool {return _storage._ratchetState != nil}
  /// Clears the value of `ratchetState`. Subsequent reads from it will return its default value.
  public mutating func clearRatchetState() {_uniqueStorage()._ratchetState = nil}

  public var adaptiveRatchetState: Ecliptix_Proto_Protocol_AdaptiveRatchetState {
    get {return _storage._adaptiveRatchetState ?? Ecliptix_Proto_Protocol_AdaptiveRatchetState()}
    set {_uniqueStorage()._adaptiveRatchetState = newValue}
  }
  /// Returns true if `adaptiveRatchetState` has been explicitly set.
  public var hasAdaptiveRatchetState: Bool {return _storage._adaptiveRatchetState != nil}
  /// Clears the value of `adaptiveRatchetState`. Subsequent reads from it will return its default value.
  public mutating func clearAdaptiveRatchetState() {_uniqueStorage()._adaptiveRatchetState = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Ecliptix_Proto_Protocol_IdentityKeysState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ed25519SecretKey: Data = Data()

  public var identityX25519SecretKey: Data = Data()

  public var signedPreKeySecret: Data = Data()

  public var oneTimePreKeys: [Ecliptix_Proto_Protocol_OneTimePreKeySecret] = []

  public var ed25519PublicKey: Data = Data()

  public var identityX25519PublicKey: Data = Data()

  public var signedPreKeyID: UInt32 = 0

  public var signedPreKeyPublic: Data = Data()

  public var signedPreKeySignature: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Ecliptix_Proto_Protocol_OneTimePreKeySecret: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var preKeyID: UInt32 = 0

  public var privateKey: Data = Data()

  public var publicKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Ecliptix_Proto_Protocol_RatchetState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var isInitiator: Bool {
    get {return _storage._isInitiator}
    set {_uniqueStorage()._isInitiator = newValue}
  }

  public var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  public var hasCreatedAt: Bool {return _storage._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  public mutating func clearCreatedAt() {_uniqueStorage()._createdAt = nil}

  public var nonceCounter: UInt64 {
    get {return _storage._nonceCounter}
    set {_uniqueStorage()._nonceCounter = newValue}
  }

  public var peerBundle: Ecliptix_Proto_Protocol_PublicKeyBundle {
    get {return _storage._peerBundle ?? Ecliptix_Proto_Protocol_PublicKeyBundle()}
    set {_uniqueStorage()._peerBundle = newValue}
  }
  /// Returns true if `peerBundle` has been explicitly set.
  public var hasPeerBundle: Bool {return _storage._peerBundle != nil}
  /// Clears the value of `peerBundle`. Subsequent reads from it will return its default value.
  public mutating func clearPeerBundle() {_uniqueStorage()._peerBundle = nil}

  public var peerDhPublicKey: Data {
    get {return _storage._peerDhPublicKey}
    set {_uniqueStorage()._peerDhPublicKey = newValue}
  }

  public var isFirstReceivingRatchet: Bool {
    get {return _storage._isFirstReceivingRatchet}
    set {_uniqueStorage()._isFirstReceivingRatchet = newValue}
  }

  public var rootKey: Data {
    get {return _storage._rootKey}
    set {_uniqueStorage()._rootKey = newValue}
  }

  public var sendingStep: Ecliptix_Proto_Protocol_ChainStepState {
    get {return _storage._sendingStep ?? Ecliptix_Proto_Protocol_ChainStepState()}
    set {_uniqueStorage()._sendingStep = newValue}
  }
  /// Returns true if `sendingStep` has been explicitly set.
  public var hasSendingStep: Bool {return _storage._sendingStep != nil}
  /// Clears the value of `sendingStep`. Subsequent reads from it will return its default value.
  public mutating func clearSendingStep() {_uniqueStorage()._sendingStep = nil}

  public var receivingStep: Ecliptix_Proto_Protocol_ChainStepState {
    get {return _storage._receivingStep ?? Ecliptix_Proto_Protocol_ChainStepState()}
    set {_uniqueStorage()._receivingStep = newValue}
  }
  /// Returns true if `receivingStep` has been explicitly set.
  public var hasReceivingStep: Bool {return _storage._receivingStep != nil}
  /// Clears the value of `receivingStep`. Subsequent reads from it will return its default value.
  public mutating func clearReceivingStep() {_uniqueStorage()._receivingStep = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Ecliptix_Proto_Protocol_ChainStepState: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var currentIndex: UInt32 = 0

  public var chainKey: Data = Data()

  public var dhPrivateKey: Data = Data()

  public var dhPublicKey: Data = Data()

  public var cachedMessageKeys: [Ecliptix_Proto_Protocol_CachedMessageKey] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Ecliptix_Proto_Protocol_CachedMessageKey: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var index: UInt32 = 0

  public var keyMaterial: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Ecliptix_Proto_Protocol_AdaptiveRatchetState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var currentLoad: Ecliptix_Proto_Protocol_LoadLevel = .light

  public var currentConfig: Ecliptix_Proto_Protocol_RatchetConfigState {
    get {return _currentConfig ?? Ecliptix_Proto_Protocol_RatchetConfigState()}
    set {_currentConfig = newValue}
  }
  /// Returns true if `currentConfig` has been explicitly set.
  public var hasCurrentConfig: Bool {return self._currentConfig != nil}
  /// Clears the value of `currentConfig`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentConfig() {self._currentConfig = nil}

  public var averageMessageRate: Double = 0

  public var lastConfigUpdate: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _lastConfigUpdate ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_lastConfigUpdate = newValue}
  }
  /// Returns true if `lastConfigUpdate` has been explicitly set.
  public var hasLastConfigUpdate: Bool {return self._lastConfigUpdate != nil}
  /// Clears the value of `lastConfigUpdate`. Subsequent reads from it will return its default value.
  public mutating func clearLastConfigUpdate() {self._lastConfigUpdate = nil}

  public var recentMessageTimestamps: [SwiftProtobuf.Google_Protobuf_Timestamp] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _currentConfig: Ecliptix_Proto_Protocol_RatchetConfigState? = nil
  fileprivate var _lastConfigUpdate: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct Ecliptix_Proto_Protocol_RatchetConfigState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var dhRatchetEveryNMessages: UInt32 = 0

  public var enablePerMessageRatchet: Bool = false

  public var ratchetOnNewDhKey: Bool = false

  public var maxChainAge: SwiftProtobuf.Google_Protobuf_Duration {
    get {return _maxChainAge ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_maxChainAge = newValue}
  }
  /// Returns true if `maxChainAge` has been explicitly set.
  public var hasMaxChainAge: Bool {return self._maxChainAge != nil}
  /// Clears the value of `maxChainAge`. Subsequent reads from it will return its default value.
  public mutating func clearMaxChainAge() {self._maxChainAge = nil}

  public var maxMessagesWithoutRatchet: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _maxChainAge: SwiftProtobuf.Google_Protobuf_Duration? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "ecliptix.proto.protocol"

extension Ecliptix_Proto_Protocol_LoadLevel: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "LIGHT"),
    1: .same(proto: "MODERATE"),
    2: .same(proto: "HEAVY"),
    3: .same(proto: "EXTREME"),
  ]
}

extension Ecliptix_Proto_Protocol_EcliptixSessionState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EcliptixSessionState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "connect_id"),
    2: .standard(proto: "identity_keys"),
    3: .standard(proto: "peer_handshake_message"),
    4: .standard(proto: "ratchet_state"),
    5: .standard(proto: "adaptive_ratchet_state"),
  ]

  fileprivate class _StorageClass {
    var _connectID: UInt32 = 0
    var _identityKeys: Ecliptix_Proto_Protocol_IdentityKeysState? = nil
    var _peerHandshakeMessage: Ecliptix_Proto_Protocol_PubKeyExchange? = nil
    var _ratchetState: Ecliptix_Proto_Protocol_RatchetState? = nil
    var _adaptiveRatchetState: Ecliptix_Proto_Protocol_AdaptiveRatchetState? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _connectID = source._connectID
      _identityKeys = source._identityKeys
      _peerHandshakeMessage = source._peerHandshakeMessage
      _ratchetState = source._ratchetState
      _adaptiveRatchetState = source._adaptiveRatchetState
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularUInt32Field(value: &_storage._connectID) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._identityKeys) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._peerHandshakeMessage) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._ratchetState) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._adaptiveRatchetState) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._connectID != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._connectID, fieldNumber: 1)
      }
      try { if let v = _storage._identityKeys {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._peerHandshakeMessage {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._ratchetState {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._adaptiveRatchetState {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Protocol_EcliptixSessionState, rhs: Ecliptix_Proto_Protocol_EcliptixSessionState) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._connectID != rhs_storage._connectID {return false}
        if _storage._identityKeys != rhs_storage._identityKeys {return false}
        if _storage._peerHandshakeMessage != rhs_storage._peerHandshakeMessage {return false}
        if _storage._ratchetState != rhs_storage._ratchetState {return false}
        if _storage._adaptiveRatchetState != rhs_storage._adaptiveRatchetState {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Protocol_IdentityKeysState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IdentityKeysState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "ed25519_secret_key"),
    2: .standard(proto: "identity_x25519_secret_key"),
    4: .standard(proto: "signed_pre_key_secret"),
    5: .standard(proto: "one_time_pre_keys"),
    10: .standard(proto: "ed25519_public_key"),
    11: .standard(proto: "identity_x25519_public_key"),
    12: .standard(proto: "signed_pre_key_id"),
    13: .standard(proto: "signed_pre_key_public"),
    14: .standard(proto: "signed_pre_key_signature"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.ed25519SecretKey) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.identityX25519SecretKey) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.signedPreKeySecret) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.oneTimePreKeys) }()
      case 10: try { try decoder.decodeSingularBytesField(value: &self.ed25519PublicKey) }()
      case 11: try { try decoder.decodeSingularBytesField(value: &self.identityX25519PublicKey) }()
      case 12: try { try decoder.decodeSingularUInt32Field(value: &self.signedPreKeyID) }()
      case 13: try { try decoder.decodeSingularBytesField(value: &self.signedPreKeyPublic) }()
      case 14: try { try decoder.decodeSingularBytesField(value: &self.signedPreKeySignature) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ed25519SecretKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ed25519SecretKey, fieldNumber: 1)
    }
    if !self.identityX25519SecretKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.identityX25519SecretKey, fieldNumber: 2)
    }
    if !self.signedPreKeySecret.isEmpty {
      try visitor.visitSingularBytesField(value: self.signedPreKeySecret, fieldNumber: 4)
    }
    if !self.oneTimePreKeys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.oneTimePreKeys, fieldNumber: 5)
    }
    if !self.ed25519PublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ed25519PublicKey, fieldNumber: 10)
    }
    if !self.identityX25519PublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.identityX25519PublicKey, fieldNumber: 11)
    }
    if self.signedPreKeyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.signedPreKeyID, fieldNumber: 12)
    }
    if !self.signedPreKeyPublic.isEmpty {
      try visitor.visitSingularBytesField(value: self.signedPreKeyPublic, fieldNumber: 13)
    }
    if !self.signedPreKeySignature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signedPreKeySignature, fieldNumber: 14)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Protocol_IdentityKeysState, rhs: Ecliptix_Proto_Protocol_IdentityKeysState) -> Bool {
    if lhs.ed25519SecretKey != rhs.ed25519SecretKey {return false}
    if lhs.identityX25519SecretKey != rhs.identityX25519SecretKey {return false}
    if lhs.signedPreKeySecret != rhs.signedPreKeySecret {return false}
    if lhs.oneTimePreKeys != rhs.oneTimePreKeys {return false}
    if lhs.ed25519PublicKey != rhs.ed25519PublicKey {return false}
    if lhs.identityX25519PublicKey != rhs.identityX25519PublicKey {return false}
    if lhs.signedPreKeyID != rhs.signedPreKeyID {return false}
    if lhs.signedPreKeyPublic != rhs.signedPreKeyPublic {return false}
    if lhs.signedPreKeySignature != rhs.signedPreKeySignature {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Protocol_OneTimePreKeySecret: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OneTimePreKeySecret"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "pre_key_id"),
    2: .standard(proto: "private_key"),
    3: .standard(proto: "public_key"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.preKeyID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.privateKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.publicKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.preKeyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.preKeyID, fieldNumber: 1)
    }
    if !self.privateKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.privateKey, fieldNumber: 2)
    }
    if !self.publicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.publicKey, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Protocol_OneTimePreKeySecret, rhs: Ecliptix_Proto_Protocol_OneTimePreKeySecret) -> Bool {
    if lhs.preKeyID != rhs.preKeyID {return false}
    if lhs.privateKey != rhs.privateKey {return false}
    if lhs.publicKey != rhs.publicKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Protocol_RatchetState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RatchetState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "is_initiator"),
    2: .standard(proto: "created_at"),
    3: .standard(proto: "nonce_counter"),
    4: .standard(proto: "peer_bundle"),
    5: .standard(proto: "peer_dh_public_key"),
    6: .standard(proto: "is_first_receiving_ratchet"),
    10: .standard(proto: "root_key"),
    11: .standard(proto: "sending_step"),
    12: .standard(proto: "receiving_step"),
  ]

  fileprivate class _StorageClass {
    var _isInitiator: Bool = false
    var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _nonceCounter: UInt64 = 0
    var _peerBundle: Ecliptix_Proto_Protocol_PublicKeyBundle? = nil
    var _peerDhPublicKey: Data = Data()
    var _isFirstReceivingRatchet: Bool = false
    var _rootKey: Data = Data()
    var _sendingStep: Ecliptix_Proto_Protocol_ChainStepState? = nil
    var _receivingStep: Ecliptix_Proto_Protocol_ChainStepState? = nil

    #if swift(>=5.10)
      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()
    #else
      static let defaultInstance = _StorageClass()
    #endif

    private init() {}

    init(copying source: _StorageClass) {
      _isInitiator = source._isInitiator
      _createdAt = source._createdAt
      _nonceCounter = source._nonceCounter
      _peerBundle = source._peerBundle
      _peerDhPublicKey = source._peerDhPublicKey
      _isFirstReceivingRatchet = source._isFirstReceivingRatchet
      _rootKey = source._rootKey
      _sendingStep = source._sendingStep
      _receivingStep = source._receivingStep
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularBoolField(value: &_storage._isInitiator) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._createdAt) }()
        case 3: try { try decoder.decodeSingularUInt64Field(value: &_storage._nonceCounter) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._peerBundle) }()
        case 5: try { try decoder.decodeSingularBytesField(value: &_storage._peerDhPublicKey) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._isFirstReceivingRatchet) }()
        case 10: try { try decoder.decodeSingularBytesField(value: &_storage._rootKey) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._sendingStep) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._receivingStep) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._isInitiator != false {
        try visitor.visitSingularBoolField(value: _storage._isInitiator, fieldNumber: 1)
      }
      try { if let v = _storage._createdAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if _storage._nonceCounter != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._nonceCounter, fieldNumber: 3)
      }
      try { if let v = _storage._peerBundle {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      if !_storage._peerDhPublicKey.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._peerDhPublicKey, fieldNumber: 5)
      }
      if _storage._isFirstReceivingRatchet != false {
        try visitor.visitSingularBoolField(value: _storage._isFirstReceivingRatchet, fieldNumber: 6)
      }
      if !_storage._rootKey.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._rootKey, fieldNumber: 10)
      }
      try { if let v = _storage._sendingStep {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._receivingStep {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Protocol_RatchetState, rhs: Ecliptix_Proto_Protocol_RatchetState) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._isInitiator != rhs_storage._isInitiator {return false}
        if _storage._createdAt != rhs_storage._createdAt {return false}
        if _storage._nonceCounter != rhs_storage._nonceCounter {return false}
        if _storage._peerBundle != rhs_storage._peerBundle {return false}
        if _storage._peerDhPublicKey != rhs_storage._peerDhPublicKey {return false}
        if _storage._isFirstReceivingRatchet != rhs_storage._isFirstReceivingRatchet {return false}
        if _storage._rootKey != rhs_storage._rootKey {return false}
        if _storage._sendingStep != rhs_storage._sendingStep {return false}
        if _storage._receivingStep != rhs_storage._receivingStep {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Protocol_ChainStepState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ChainStepState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "current_index"),
    2: .standard(proto: "chain_key"),
    3: .standard(proto: "dh_private_key"),
    4: .standard(proto: "dh_public_key"),
    5: .standard(proto: "cached_message_keys"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.currentIndex) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.chainKey) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.dhPrivateKey) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.dhPublicKey) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.cachedMessageKeys) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.currentIndex != 0 {
      try visitor.visitSingularUInt32Field(value: self.currentIndex, fieldNumber: 1)
    }
    if !self.chainKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.chainKey, fieldNumber: 2)
    }
    if !self.dhPrivateKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.dhPrivateKey, fieldNumber: 3)
    }
    if !self.dhPublicKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.dhPublicKey, fieldNumber: 4)
    }
    if !self.cachedMessageKeys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.cachedMessageKeys, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Protocol_ChainStepState, rhs: Ecliptix_Proto_Protocol_ChainStepState) -> Bool {
    if lhs.currentIndex != rhs.currentIndex {return false}
    if lhs.chainKey != rhs.chainKey {return false}
    if lhs.dhPrivateKey != rhs.dhPrivateKey {return false}
    if lhs.dhPublicKey != rhs.dhPublicKey {return false}
    if lhs.cachedMessageKeys != rhs.cachedMessageKeys {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Protocol_CachedMessageKey: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CachedMessageKey"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "index"),
    2: .standard(proto: "key_material"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.index) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.keyMaterial) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.index != 0 {
      try visitor.visitSingularUInt32Field(value: self.index, fieldNumber: 1)
    }
    if !self.keyMaterial.isEmpty {
      try visitor.visitSingularBytesField(value: self.keyMaterial, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Protocol_CachedMessageKey, rhs: Ecliptix_Proto_Protocol_CachedMessageKey) -> Bool {
    if lhs.index != rhs.index {return false}
    if lhs.keyMaterial != rhs.keyMaterial {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Protocol_AdaptiveRatchetState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AdaptiveRatchetState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "current_load"),
    2: .standard(proto: "current_config"),
    3: .standard(proto: "average_message_rate"),
    4: .standard(proto: "last_config_update"),
    5: .standard(proto: "recent_message_timestamps"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.currentLoad) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._currentConfig) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.averageMessageRate) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._lastConfigUpdate) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.recentMessageTimestamps) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.currentLoad != .light {
      try visitor.visitSingularEnumField(value: self.currentLoad, fieldNumber: 1)
    }
    try { if let v = self._currentConfig {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if self.averageMessageRate.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.averageMessageRate, fieldNumber: 3)
    }
    try { if let v = self._lastConfigUpdate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.recentMessageTimestamps.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.recentMessageTimestamps, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Protocol_AdaptiveRatchetState, rhs: Ecliptix_Proto_Protocol_AdaptiveRatchetState) -> Bool {
    if lhs.currentLoad != rhs.currentLoad {return false}
    if lhs._currentConfig != rhs._currentConfig {return false}
    if lhs.averageMessageRate != rhs.averageMessageRate {return false}
    if lhs._lastConfigUpdate != rhs._lastConfigUpdate {return false}
    if lhs.recentMessageTimestamps != rhs.recentMessageTimestamps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Ecliptix_Proto_Protocol_RatchetConfigState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RatchetConfigState"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "dh_ratchet_every_n_messages"),
    2: .standard(proto: "enable_per_message_ratchet"),
    3: .standard(proto: "ratchet_on_new_dh_key"),
    4: .standard(proto: "max_chain_age"),
    5: .standard(proto: "max_messages_without_ratchet"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.dhRatchetEveryNMessages) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.enablePerMessageRatchet) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.ratchetOnNewDhKey) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._maxChainAge) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.maxMessagesWithoutRatchet) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.dhRatchetEveryNMessages != 0 {
      try visitor.visitSingularUInt32Field(value: self.dhRatchetEveryNMessages, fieldNumber: 1)
    }
    if self.enablePerMessageRatchet != false {
      try visitor.visitSingularBoolField(value: self.enablePerMessageRatchet, fieldNumber: 2)
    }
    if self.ratchetOnNewDhKey != false {
      try visitor.visitSingularBoolField(value: self.ratchetOnNewDhKey, fieldNumber: 3)
    }
    try { if let v = self._maxChainAge {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if self.maxMessagesWithoutRatchet != 0 {
      try visitor.visitSingularUInt32Field(value: self.maxMessagesWithoutRatchet, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Ecliptix_Proto_Protocol_RatchetConfigState, rhs: Ecliptix_Proto_Protocol_RatchetConfigState) -> Bool {
    if lhs.dhRatchetEveryNMessages != rhs.dhRatchetEveryNMessages {return false}
    if lhs.enablePerMessageRatchet != rhs.enablePerMessageRatchet {return false}
    if lhs.ratchetOnNewDhKey != rhs.ratchetOnNewDhKey {return false}
    if lhs._maxChainAge != rhs._maxChainAge {return false}
    if lhs.maxMessagesWithoutRatchet != rhs.maxMessagesWithoutRatchet {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
